// Country code to flag emoji mapping
export const countryFlags: Record<string, string> = {
  CN: '🇨🇳',
  US: '🇺🇸',
  GB: '🇬🇧',
  IN: '🇮🇳',
  RU: '🇷🇺',
  ID: '🇮🇩',
  BR: '🇧🇷',
  DE: '🇩🇪',
  FR: '🇫🇷',
  JP: '🇯🇵',
  KR: '🇰🇷',
  VN: '🇻🇳',
  TH: '🇹🇭',
  PH: '🇵🇭',
  MY: '🇲🇾',
  SG: '🇸🇬',
  AU: '🇦🇺',
  CA: '🇨🇦',
  MX: '🇲🇽',
  ES: '🇪🇸',
  IT: '🇮🇹',
  NL: '🇳🇱',
  PL: '🇵🇱',
  TR: '🇹🇷',
  ZA: '🇿🇦',
  NG: '🇳🇬',
  EG: '🇪🇬',
  AE: '🇦🇪',
  SA: '🇸🇦',
  AR: '🇦🇷',
  CL: '🇨🇱',
  CO: '🇨🇴',
  PE: '🇵🇪',
  VE: '🇻🇪',
  PK: '🇵🇰',
  BD: '🇧🇩',
  MM: '🇲🇲',
  NP: '🇳🇵',
  LK: '🇱🇰',
  KH: '🇰🇭',
  LA: '🇱🇦',
  TW: '🇹🇼',
  HK: '🇭🇰',
  MO: '🇲🇴',
  NZ: '🇳🇿',
  AT: '🇦🇹',
  BE: '🇧🇪',
  CH: '🇨🇭',
  CZ: '🇨🇿',
  DK: '🇩🇰',
  FI: '🇫🇮',
  GR: '🇬🇷',
  HU: '🇭🇺',
  IE: '🇮🇪',
  NO: '🇳🇴',
  PT: '🇵🇹',
  RO: '🇷🇴',
  SE: '🇸🇪',
  UA: '🇺🇦',
  BY: '🇧🇾',
  KZ: '🇰🇿',
  UZ: '🇺🇿',
  IL: '🇮🇱',
  IQ: '🇮🇶',
  IR: '🇮🇷',
  JO: '🇯🇴',
  KW: '🇰🇼',
  LB: '🇱🇧',
  OM: '🇴🇲',
  QA: '🇶🇦',
  BH: '🇧🇭',
  YE: '🇾🇪',
  MA: '🇲🇦',
  DZ: '🇩🇿',
  TN: '🇹🇳',
  LY: '🇱🇾',
  KE: '🇰🇪',
  GH: '🇬🇭',
  ET: '🇪🇹',
  TZ: '🇹🇿',
  UG: '🇺🇬',
  CM: '🇨🇲',
  CI: '🇨🇮',
  SN: '🇸🇳',
  EC: '🇪🇨',
  BO: '🇧🇴',
  PY: '🇵🇾',
  UY: '🇺🇾',
  DO: '🇩🇴',
  CR: '🇨🇷',
  PA: '🇵🇦',
  GT: '🇬🇹',
  HN: '🇭🇳',
  SV: '🇸🇻',
  NI: '🇳🇮',
  CU: '🇨🇺',
  JM: '🇯🇲',
  HT: '🇭🇹',
  SK: '🇸🇰',
  HR: '🇭🇷',
  RS: '🇷🇸',
  BG: '🇧🇬',
  SI: '🇸🇮',
  LT: '🇱🇹',
  LV: '🇱🇻',
  EE: '🇪🇪',
};

// Get flag emoji from country code
export const getCountryFlag = (code: string): string => {
  return countryFlags[code.toUpperCase()] || '🏳️';
};

// Get the first character as icon for a service
export const getServiceFirstCharIcon = (name: string): string => {
  if (!name) return '📱';
  return name.charAt(0);
};

// Country code to English name mapping
export const countryNamesEn: Record<string, string> = {
  CN: 'China',
  US: 'United States',
  GB: 'United Kingdom',
  IN: 'India',
  RU: 'Russia',
  ID: 'Indonesia',
  BR: 'Brazil',
  DE: 'Germany',
  FR: 'France',
  JP: 'Japan',
  KR: 'South Korea',
  VN: 'Vietnam',
  TH: 'Thailand',
  PH: 'Philippines',
  MY: 'Malaysia',
  SG: 'Singapore',
  AU: 'Australia',
  CA: 'Canada',
  MX: 'Mexico',
  ES: 'Spain',
  IT: 'Italy',
  NL: 'Netherlands',
  PL: 'Poland',
  TR: 'Turkey',
  ZA: 'South Africa',
  NG: 'Nigeria',
  EG: 'Egypt',
  AE: 'UAE',
  SA: 'Saudi Arabia',
  AR: 'Argentina',
  CL: 'Chile',
  CO: 'Colombia',
  PE: 'Peru',
  VE: 'Venezuela',
  PK: 'Pakistan',
  BD: 'Bangladesh',
  MM: 'Myanmar',
  NP: 'Nepal',
  LK: 'Sri Lanka',
  KH: 'Cambodia',
  LA: 'Laos',
  TW: 'Taiwan',
  HK: 'Hong Kong',
  MO: 'Macao',
  NZ: 'New Zealand',
  AT: 'Austria',
  BE: 'Belgium',
  CH: 'Switzerland',
  CZ: 'Czech Republic',
  DK: 'Denmark',
  FI: 'Finland',
  GR: 'Greece',
  HU: 'Hungary',
  IE: 'Ireland',
  NO: 'Norway',
  PT: 'Portugal',
  RO: 'Romania',
  SE: 'Sweden',
  UA: 'Ukraine',
  BY: 'Belarus',
  KZ: 'Kazakhstan',
  UZ: 'Uzbekistan',
  IL: 'Israel',
  IQ: 'Iraq',
  IR: 'Iran',
  JO: 'Jordan',
  KW: 'Kuwait',
  LB: 'Lebanon',
  OM: 'Oman',
  QA: 'Qatar',
  BH: 'Bahrain',
  YE: 'Yemen',
  MA: 'Morocco',
  DZ: 'Algeria',
  TN: 'Tunisia',
  LY: 'Libya',
  KE: 'Kenya',
  GH: 'Ghana',
  ET: 'Ethiopia',
  TZ: 'Tanzania',
  UG: 'Uganda',
  CM: 'Cameroon',
  CI: 'Ivory Coast',
  SN: 'Senegal',
  EC: 'Ecuador',
  BO: 'Bolivia',
  PY: 'Paraguay',
  UY: 'Uruguay',
  DO: 'Dominican Republic',
  CR: 'Costa Rica',
  PA: 'Panama',
  GT: 'Guatemala',
  HN: 'Honduras',
  SV: 'El Salvador',
  NI: 'Nicaragua',
  CU: 'Cuba',
  JM: 'Jamaica',
  HT: 'Haiti',
  SK: 'Slovakia',
  HR: 'Croatia',
  RS: 'Serbia',
  BG: 'Bulgaria',
  SI: 'Slovenia',
  LT: 'Lithuania',
  LV: 'Latvia',
  EE: 'Estonia',
};

// Get country region from code
export const getCountryRegion = (code: string): string => {
  const asiaCountries = ['CN', 'IN', 'ID', 'JP', 'KR', 'VN', 'TH', 'PH', 'MY', 'SG', 'PK', 'BD', 'MM', 'NP', 'LK', 'KH', 'LA', 'TW', 'HK', 'MO', 'AE', 'SA', 'IL', 'IQ', 'IR', 'JO', 'KW', 'LB', 'OM', 'QA', 'BH', 'YE', 'KZ', 'UZ'];
  const europeCountries = ['GB', 'RU', 'DE', 'FR', 'ES', 'IT', 'NL', 'PL', 'TR', 'AT', 'BE', 'CH', 'CZ', 'DK', 'FI', 'GR', 'HU', 'IE', 'NO', 'PT', 'RO', 'SE', 'UA', 'BY', 'SK', 'HR', 'RS', 'BG', 'SI', 'LT', 'LV', 'EE'];
  const americasCountries = ['US', 'BR', 'CA', 'MX', 'AR', 'CL', 'CO', 'PE', 'VE', 'EC', 'BO', 'PY', 'UY', 'DO', 'CR', 'PA', 'GT', 'HN', 'SV', 'NI', 'CU', 'JM', 'HT'];
  const africaCountries = ['ZA', 'NG', 'EG', 'MA', 'DZ', 'TN', 'LY', 'KE', 'GH', 'ET', 'TZ', 'UG', 'CM', 'CI', 'SN'];
  const oceaniaCountries = ['AU', 'NZ'];
  
  if (asiaCountries.includes(code)) return 'asia';
  if (europeCountries.includes(code)) return 'europe';
  if (americasCountries.includes(code)) return 'americas';
  if (africaCountries.includes(code)) return 'africa';
  if (oceaniaCountries.includes(code)) return 'oceania';
  return 'other';
};
