// Service icon mapping utility
export const getServiceIcon = (iconName: string | null): string => {
  const iconMap: Record<string, string> = {
    whatsapp: '💬',
    telegram: '✈️',
    google: '🔍',
    facebook: '👤',
    twitter: '🐦',
    instagram: '📷',
    tiktok: '🎵',
    wechat: '💚',
    alipay: '💰',
    discord: '🎮',
    snapchat: '👻',
    linkedin: '💼',
    microsoft: '🪟',
    apple: '🍎',
    amazon: '📦',
    netflix: '🎬',
    uber: '🚗',
    paypal: '💳',
    binance: '🪙',
    okx: '📊',
    coinbase: '💎',
    steam: '🎮',
    line: '💬',
    viber: '📞',
    tinder: '❤️',
    youtube: '▶️',
    spotify: '🎧',
    twitch: '🟣',
    reddit: '🔶',
    pinterest: '📌',
    tumblr: '📝',
    skype: '📞',
    zoom: '📹',
    slack: '💼',
    weibo: '🔴',
    qq: '🐧',
    baidu: '🔍',
    jd: '🛒',
    taobao: '🛍️',
    meituan: '🍽️',
    didi: '🚕',
    douyin: '🎵',
    kuaishou: '📹',
    bilibili: '📺',
  };

  return iconMap[iconName || ''] || '📱';
};
